language: java

sudo: false

jdk:
  - openjdk11

services:
  - postgresql

before_install:
  - psql -c 'create database url_shortcut;' -U postgres

install: true

script: mvn clean package

notifications:
  email:
    recipients:
    - gh0st84@mail.ru
    on_success: never
    on_failure: always

